// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using TinyIoC;

namespace App.iOS
{
	public partial class EchoViewController : UIViewController
	{
		public EchoViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// As we already registered the components/services in the AppDelegate's FinishedLaunching
			// method, we can now resolve components/services
			var echoService = TinyIoCContainer.Current.Resolve<EchoService>();

			this.EchoLabel.Text = echoService.Echo();
		}
	}
}
